version: '3.8'

services:
  youtube-automation:
    build: .
    container_name: youtube-automation
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./videos:/app/videos
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - youtube-net
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    container_name: youtube-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - youtube-net

  postgres:
    image: postgres:15-alpine
    container_name: youtube-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: youtube_automation
      POSTGRES_USER: youtube_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - youtube-net

  nginx:
    image: nginx:alpine
    container_name: youtube-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - youtube-net
    depends_on:
      - youtube-automation

volumes:
  redis_data:
  postgres_data:

networks:
  youtube-net:
    driver: bridge